app/frontend/urls.py
from django.urls import path

from frontend.views import home, report

app_name = "frontend"
urlpatterns = [
    path("", home, name="home"),
    path("report/<uuid:file_uid>", report, name="report"),
]

app/users/urls.py
from django.urls import path

from .views import (
    user_detail_view,
    user_redirect_view,
    user_update_view,
)

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views

urlpatterns = [
    path("", include("frontend.urls")),
    path(settings.ADMIN_URL, admin.site.urls),
    path("users/", include("users.urls")),
    path("accounts/", include("allauth.urls")),
    path("", include("api.urls")),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

app/templates/base.html
{% load static i18n %}<!DOCTYPE html>
{% get_current_language as LANGUAGE_CODE %}
<html lang="{{ LANGUAGE_CODE }}">
<head>
  <meta charset="utf-8">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <title>{% block title %}Test task for skypro{% endblock title %}</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="Code quality service aka test task for skypro">
  <meta name="author" content="Mescheryakov Alexander">
  <link rel="icon" href="{% static 'images/favicons/favicon.ico' %}">
  {% block css %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">
    <link href="{% static 'css/project.css' %}" rel="stylesheet">
  {% endblock %}
  {% block javascript %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
            crossorigin="anonymous"></script>
    <script defer src="{% static 'js/project.js' %}"></script>
  {% endblock javascript %}

</head>

<body>

<div class="mb-1">
  <nav class="navbar navbar-expand-md navbar-light bg-light">
    <div class="container-fluid">
      <button class="navbar-toggler navbar-toggler-right" type="button" data-bs-toggle="collapse"
              data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
              aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <a class="navbar-brand" href="{% url 'frontend:home' %}">S</a>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav w-100 d-flex justify-content-between">
          <div class="d-flex justify-content-start">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'frontend:home' %}">Home <span
                class="visually-hidden">(current)</span></a>
            </li>
            {% if user.is_superuser %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'api:api-docs_v1' %}">API Docs</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
              </li>
            {% endif %}
          </div>
          <div class="d-flex justify-content-end">
            {% if request.user.is_authenticated %}
              <li class="nav-item ml-auto">
                <a class="nav-link"
                   href="{% url 'users:detail' request.user.username %}">{% translate "My Profile" %}</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'account_logout' %}">{% translate "Sign Out" %}</a>
              </li>

            {% else %}
              {% if ACCOUNT_ALLOW_REGISTRATION %}
                <li class="nav-item">
                  <a id="sign-up-link" class="nav-link" href="{% url 'account_signup' %}">{% translate "Sign Up" %}</a>
                </li>
              {% endif %}
              <li class="nav-item">
                <a id="log-in-link" class="nav-link" href="{% url 'account_login' %}">{% translate "Sign In" %}</a>
              </li>
            {% endif %}
          </div>

        </ul>
      </div>
    </div>
  </nav>

</div>

<div class="container">
  {% if messages %}
    {% for message in messages %}
      <div class="alert alert-dismissible {% if message.tags %}alert-{{ message.tags }}{% endif %}">
        {{ message }}
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
    {% endfor %}
  {% endif %}
  {% block content %}



  {% endblock content %}

</div>

{% block modal %}{% endblock modal %}

{% block inline_javascript %}
{% endblock inline_javascript %}
</body>
</html>